FROM arm64v8/ubuntu:20.04

# Fetch Kubectl
RUN curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.17.3/bin/linux/arm64/kubectl
RUN chmod +x kubectl && mv kubectl /bin/

# Copy drone-kubernetes binary
COPY drone-kubernetes /bin/

ENTRYPOINT ["/bin/drone-kubernetes"]