FROM golang:alpine AS builder
ENV GOARCH=arm64 GOOS=linux CGO_ENABLED=0

RUN apk add --no-cache curl unzip bash

WORKDIR /build
COPY .. .

# Fetch Kubectl
RUN curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.17.3/bin/linux/arm64/kubectl
RUN chmod +x kubectl

# Fetch kustomize
## For now Kustomize doesn't work on ARMV6
#RUN curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash

FROM arm64v8/ubuntu:20.04 as arm64

# Copy binaries
COPY --from=builder /build/drone-kubernetes /bin/
COPY --from=builder /build/kubectl /bin/
#COPY --from=builder /build/aws .
#COPY --from=builder /build/kustomize /bin/

# Install AWSCli
#RUN ./install -b /bin/

ENTRYPOINT ["/bin/drone-kubernetes"]